#!/usr/bin/env python
import os
import sys
import getopt
import twitter

#Declare globals
api = None

def usage():
    print('Usage: see the wiki (this will get fixed later')

def tweet(message):
    """Set your status to <message>."""
    status = api.PostUpdate(message)

def authenticatedList(authenticatedUsername):
    global api
    # Get our username from the global api var
    statuses = api.GetFriendsTimeline(authenticatedUsername)
    printStatuses(statuses)

def unauthenticatedList(username):
    global api
    statuses = api.GetUserTimeline(username)
    printStatuses(statuses)

def printStatuses(statuses):
    for status in statuses:
        user = status.GetUser()
        username = user.GetName()
        message = status.GetText()
        print "%s: %s\n" % (username, message)
    sys.exit(1)


def main(argv):
    username = ""
    password = ""
    action = "noaction"
    try:
        opts, args = getopt.getopt(argv, "f:hlop:t:u:", ["friend", "help", "list", "own", "password", "tweet", "username"])
    except getopt.error:
        usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-f", "--friend"):
            action = "listfriend"
            targetUser = arg
        elif opt in ("-h", "--help"):
            usage()
            sys.exit()
        elif opt in ("-l", "--list"):
            action = "list"
        elif opt in ("-o", "--own"):
            action = "listown"
        elif opt in ("-p", "--password"):
            password = arg
        elif opt in ("-t", "--tweet"):
            action = "tweet"
            tweetMessage = arg
        elif opt in ("-u", "--username"):
            username = arg
    global api # Let our function know we mean the global api
    if username and password:
        api = twitter.Api(username=username, password=password)
    else:
        api = twitter.Api()
    if action in ("list", "listfriend", "listown"):
        if action in ("listown"):
            if username:
                targetUser = username
            else:
                print "A username must be supplied to get your list"
                sys.exit(-1)
        if action in ("listfriend", "listown"):
            unauthenticatedList(targetUser)
        elif action in ("list"):
            if username and password:
                authenticatedList(username)
            else:
                print "A username and password must be supplied to that list"
                sys.exit(-1)
    elif action in ("tweet"):
            if username and password:
                tweet(tweetMessage)
            else:
                print "Username and password must be supplied to post a tweet"
                sys.exit(-1)
    elif action in ("noaction"):
        print "You gotta tell me to do something"

if __name__ == "__main__":
    main(sys.argv[1:])
